import sys
numbers = ['1', '2', '3','4','5','6','7','8','9','10','11','12','13','14','15']
for test in numbers:
    sys.stdout.write('\nA')
    sys.stdout.write(test)
    sys.stdout.write(' = " "')
    sys.stdout.flush()
sys.stdout.write('\nsheet.update_acell(')
sys.stdout.write('"A1", A1)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A2", A2)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A3", A3)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A4", A4)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A5", A5)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A6", A6)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A7", A7)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A8", A8)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A9", A9)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A10", A10)\n') 
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A11", A11)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A12", A12)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A13", A13)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A14", A14)\n')
sys.stdout.write('sheet.update_acell(')
sys.stdout.write('"A15", A15)\n')