CREATE TABLE USERS (
    UNIQ_ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(40),
    User_PASSWORD VARCHAR(120),
    User_name VARCHAR(120),
    -- DATECREATED DATETIME NOT NULL DEFAULT(GETDATE()),
    PRIMARY KEY(UNIQ_ID)
);

CREATE TABLE SCAN_T (
  SCAN_ID INT AUTO_INCRIMENT,
  DATECREATED DATETIME NOT NULL DEFAULT(GETDATE()),
  PRIMARY KEY (SCAN_ID),
  FOREIGN KEY REFERENCES USER_INFO(UNIQ_ID)
);

CREATE TABLE JSON_DATA (
  SCAN_ID INT
);
